version: '3'
services:
  web:
    build:
      context: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/hungershack
    depends_on:
      - db
  db:
    image: ntboes/postgres-uuid
