
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: hsdb_clandestine
  password: m4g1c5auc3!
  host: db

development:
  <<: *default
  database: HungerShack_development

test:
  <<: *default
  database: HungerShack_test

production:
  <<: *default
  database: HungerShack_production
  username: HungerShack
  password: <%= ENV['HUNGERSHACK_DATABASE_PASSWORD'] %>
